# Generated by Django 4.1.3 on 2022-12-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='titulo')),
                ('description', models.TextField(max_length=255, verbose_name='Descripcion')),
                ('url_github', models.TextField(max_length=255, verbose_name='URL')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagen')),
                ('tags', models.CharField(max_length=100, verbose_name='Tags')),
            ],
            options={
                'db_table': 'proyect_item',
            },
        )
    ]
