# Generated by Django 4.1.3 on 2022-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'visitor_ip',
            },
        ),
    ]
