# Generated by Django 4.1.3 on 2022-12-10 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_visitorip'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorip',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
