# Generated by Django 4.1.3 on 2022-12-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_visitorip_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorip',
            name='create_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='visitorip',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
