# Generated by Django 4.1.3 on 2022-12-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_alter_visitorip_create_at_alter_visitorip_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorip',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
    ]
