# Generated by Django 4.1.3 on 2022-12-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_alter_visitorip_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorip',
            name='create_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
